[package]
name = "get_links"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
regex = "1.10.4"
reqwest = "0.11.12"
select = "0.5.0" #select specific things from the page
tokio = { version = "1.21.1", features = ["full"] }
